version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sumo-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zhyb0ayjfn31"
s3_prefix = "sumo-test"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VpcId=\"vpc-0e9dfa6c9665fc9ed\" PrivateSubnetIds=\"subnet-0ad5c5d9278b5a8d0,subnet-03e6f531e3ad5e139\" Image=\"691777775550.dkr.ecr.us-west-2.amazonaws.com/sumo-api:latest\""
image_repositories = []
