version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sumo-manual-deploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zhyb0ayjfn31"
s3_prefix = "sumo-manual-deploy"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
